### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by progfolio** [kofm/harpoon.el#1]
Are you aware of this implementation?

https://github.com/otavioschwanck/harpoon.el

If so, it may be worth pointing out how your implementation is different.

**Comment by kofm** [comment]
Yes :) I was searching for an Harpoon implementation for Emacs when I stumbled upon a Reddit post presenting just that. Within the comments, someone mentioned that achieving Harpoon-like functionality could be effortlessly done leveraging Emacs's bookmark capabilities, so I decided to give it a shot.

I think is a good idea. I updated the README. Thank you for checking out the repo and for the feedback.
